theme: jekyll-theme-minimal
title: Knowledgbase
description: Hello from GitHub Pages + Jekyll

# Collections and post settings
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

# Post settings
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# URL configuration
baseurl: "/software-cheatsheet"
url: "https://e2xperimental.github.io"
